--create database Analisis1
use Analisis1
CREATE TABLE PROFESOR(
ID_PROFESOR INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(255),
APELLIDO VARCHAR(255),
FECHA_NAC DATE,
CARNE INT,
GENERO VARCHAR(5),
CORREO_ELECTRONICO VARCHAR(255),
TELEFONO INT,
COD_CURSOS INT,
FOREIGN KEY (COD_CURSOS) REFERENCES CURSOS(ID_CURSOS)
)

CREATE TABLE CURSOS(
ID_CURSOS INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_C VARCHAR(255),
HORARIO TIME,
REQUISITOS VARCHAR(255),
CREDITOS INT,
COD_FACULTAD INT,
FOREIGN KEY (COD_FACULTAD) REFERENCES FACULTAD(ID_FACULTAD)
)

CREATE TABLE SEMESTRE(
ID_SEMESTRE INT AUTO_INCREMENT PRIMARY KEY,
CALENDARIO DATE,
NO_SEMESTRE INT,
COD_CURSOS INT,
FOREIGN KEY (COD_CURSOS) REFERENCES CURSOS(ID_CURSOS)
)

CREATE TABLE FACULTAD(
ID_FACULTAD INT AUTO_INCREMENT PRIMARY KEY,
COD_CARRERA INT,
NOMBRE_FACU VARCHAR(255),
EDIFICIOS VARCHAR(255),
COD_SEDE INT,
COD_JORNADA INT,
COD_ESTUDIANTE INT,
FOREIGN KEY (COD_SEDE) REFERENCES SEDE(ID_SEDE),
FOREIGN KEY (COD_JORNADA) REFERENCES JORNADA(ID_JORNADA),
FOREIGN KEY (COD_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE)
)

CREATE TABLE JORNADA(
ID_JORNADA INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_JORNADA VARCHAR(255),
HORARIO TIME
)

CREATE TABLE ESTUDIANTE(
ID_ESTUDIANTE INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(255),
APELLIDO VARCHAR(255),
FECHA_NAC DATE,
CARNE INT,
CREDITOS_ACUMULADOS INT
)

CREATE TABLE TESORERIA(
ID_TESORERIA INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_PAGO VARCHAR(255),
MONTO INT,
FECHA_PAGO DATE,
COD_ESTUDIANTE INT,
FOREIGN KEY (COD_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE)
)

CREATE TABLE SEDE(
ID_SEDE INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_SEDE VARCHAR(255),
UBICACION VARCHAR(255)
)



