CREATE USER 'usuario1'@'%' IDENTIFIED BY '123456';

CREATE DATABASE asignacion;
USE asignacion;

GRANT ALL ON asignacion.* TO 'usuario1'@'%';
FLUSH PRIVILEGES;

CREATE TABLE Admin_catedratico (
ID_admin INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
Nombre VARCHAR(50) NOT NULL,
Contra VARCHAR(50) NOT NULL,
Correo VARCHAR(50) UNIQUE NOT NULL,
Direccion VARCHAR(50) NOT NULL
);

CREATE TABLE Usuario(
ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(255),
CONTRASENA VARCHAR (255)
);

INSERT INTO Usuario VALUE(1, 'javier', '1234');
SELECT *FROM Usuario;