CREATE USER 'usuario1'@'%' IDENTIFIED BY '123456';

CREATE DATABASE asignacion;
USE asignacion;

GRANT ALL ON asignacion.* TO 'usuario1'@'%';
FLUSH PRIVILEGES;

#CREACION DE CATEDRATICOS
CREATE TABLE TBL_CATEDRATICO(
ID_CATEDRATICO INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(255) NOT NULL,
APELLIDO VARCHAR(255) NOT NULL,
FECHA_NAC DATE NOT NULL,
CARNE INT NOT NULL UNIQUE,
CORREO_ELECTRONICO VARCHAR(255) NOT NULL UNIQUE,
TELEFONO INT NOT NULL UNIQUE
);

#CREACION DE ESTUDIANTE
CREATE TABLE TBL_ESTUDIANTE (
ID_ESTUDIANTE INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
FECHA_NAC DATE NOT NULL,
CARNE INT NOT NULL UNIQUE,
CREDITOS_ACUMULADOS INT NOT NULL,
ID_CARRERA INT NOT NULL,
ID_CURSOS INT NOT NULL,
SECCION VARCHAR(10) NOT NULL
);

INSERT INTO TBL_ESTUDIANTE (NOMBRE, APELLIDO, FECHA_NAC, CARNE, CREDITOS_ACUMULADOS, ID_CARRERA, ID_CURSOS, SECCION)
VALUES
('Juan', 'Pérez', '2000-01-15', 123456, 30, 101, 202, 'A'),
('María', 'García', '1999-05-20', 654321, 45, 102, 203, 'B'),
('Carlos', 'Martínez', '2001-07-10', 789012, 60, 103, 204, 'A'),
('Laura', 'López', '2000-11-25', 345678, 50, 104, 205, 'C');

#CREACION DE USUARIOS PARA LA APLICACION
CREATE TABLE TBL_USUARIOS(
ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_USUARIO VARCHAR(255) NOT NULL,
CONTRASEÑA VARCHAR(255) NOT NULL,
CORREO_ELECTRONICO VARCHAR(255) NOT NULL UNIQUE,
TIPO_USUARIO ENUM('ESTUDIANTE', 'CATEDRATICO', 'ADMINISTRADOR') NOT NULL, -- se dejo estos 3 roles para nosotros
FECHA_CREACION TIMESTAMP DEFAULT NOW() -- se puso este campo para tener registro de los usuarios
);

INSERT INTO TBL_USUARIOS (NOMBRE_USUARIO, CONTRASEÑA, CORREO_ELECTRONICO, TIPO_USUARIO)
VALUES
('admin1', 'Contra215', 'administrador1@umg.com', 'ADMINISTRADOR');